### ISSUE TITLE
JSX 元素类型 t-* 不具有任何构造签名或调用签名。ts(2604)

### ISSUE THREAD

**Issue by Mrly0** [Tencent/tdesign-starter-cli#21]
### tdesign-starter-cli 版本

v0.2.3

### 重现链接

td-starter init  => vue3

### 浏览器版本

Chrome(102.0.5005.63)

### 系统版本

win11

### Node版本

v16.14.0

**Comment by uyarn** [comment]
什么意思.. 是编辑器的提示？

**Comment by Mrly0** [comment]
> 什么英文.. 是编辑器的提示？

vscode 中的提示 运行起来不会报错
