### ISSUE TITLE
错误信息： RequestError: read ECONNRESET

### ISSUE THREAD

**Issue by Calvest** [Tencent/tdesign-starter-cli#4]
**Describe Environment**
Chrome: 版本 97.0.4692.99（正式版本） （64 位）

**Describe the bug**
构建项目时提示错误信息： RequestError: read ECONNRESET

**Additional context**
<img width="738" alt="ff76de010f4f4bd8bb6229f81fb1509" src="https://user-images.githubusercontent.com/53268471/150247009-6e7121d4-c9ed-4af4-8755-fbc989280674.png">

**Comment by uyarn** [comment]
`npm install tdesign-starter-cli@0.0.6 -g` 重新安装一下试试

**Comment by Calvest** [comment]
> `npm install tdesign-starter-cli@0.0.6 -g` 重新安装一下试试

谢谢，升级版本后正常了😀
