### ISSUE TITLE
[vue3] 通过tdesign-starter-cli构建的项目版本跟github上的版本不一致，无法获取最新版本

### ISSUE THREAD

**Issue by thx125** [Tencent/tdesign-starter-cli#40]
### tdesign-starter-cli 版本

v0.3.3

### 期望结果

能够选择模板的版本，默认拉取最新版本

**Comment by thx125** [comment]
选择包含模块： 全部，可以下载到最新的
自定义下载的版本：v0.6.1

**Comment by uyarn** [comment]
因为0.7.0之后的版本是后端权限模式 如果自定义下载没法解决权限接口的问题 目前只能用0.7之前前端权限模型的版本
