### ISSUE TITLE
[tdesign-starter-cli] 版本v0.4.2  构建版本 下载模板失败 Error: end of central directory record signature not found

### ISSUE THREAD

**Issue by SSStq1314** [Tencent/tdesign-starter-cli#54]
### tdesign-vue-starter 版本

v0.4.2 

### 重现步骤

<img width="766" alt="截屏2024-01-10 11 00 23" src="https://github.com/Tencent/tdesign-vue-starter/assets/20391773/baccd08b-6e1d-4eca-87c8-eddeb6d8178d">

### 框架版本

PC【Vue2】模板

### 系统版本

macOS

### Node版本

v20.10.0

**Comment by timi137137** [comment]
@uyarn 错误似乎来自解压缩，但我不太确定

**Comment by SSStq1314** [comment]
当我选择Lite版本的时候，可以正常下载模版创建项目，
<img width="667" alt="截屏2024-01-10 15 23 04" src="https://github.com/Tencent/tdesign-starter-cli/assets/20391773/a2c2e059-324e-4bef-9233-d0b7b33d637b">

**Comment by timi137137** [comment]
问题定位：
![image](https://github.com/Tencent/tdesign-starter-cli/assets/36812439/9129d85d-32c4-4f57-88fd-baff1b64e5c6)
但对链接之类的进行测试发现似乎没有问题，题主再试一次也会这样吗？

**Comment by SSStq1314** [comment]
是的，我刚刚又试过了两次，分别使用node 21和node 18，
还是报错返回：
 ❗错误：下载模板失败
❗错误信息： Error: end of central directory record signature not found
❗请尝试执行：git clone https://github.com/Tencent/tdesign-vue-next-starter.git 使用
executeDownload error == Error: end of central directory record signature not found
    at /Users/shaotianqi/.nvm/versions/node/v20.10.0/lib/node_modules/tdesign-starter-cli/node_modules/yauzl/index.js:187:14
    at /Users/shaotianqi/.nvm/versions/node/v20.10.0/lib/node_modules/tdesign-starter-cli/node_modules/yauzl/index.js:631:5
    at Immediate.<anonymous> (/Users/shaotianqi/.nvm/versions/node/v20.10.0/lib/node_modules/tdesign-starter-cli/node_modules/fd-slicer/index.js:202:5)
    at process.processImmediate (node:internal/timers:478:21)

**Comment by timi137137** [comment]
好的感谢题主，这边在特定尝试一下

**Comment by SSStq1314** [comment]
[捂脸][捂脸][捂脸]，我想是因为我开了vpn的问题，我刚刚把vpn关了之后，成功了， 
![Uploading 截屏2024-01-10 15.38.12.png…]()

**Comment by timi137137** [comment]
你这....

**Comment by uyarn** [comment]
reopen下 有VPN的场景确实有问题

**Comment by peterpanBest** [comment]
我也遇到了这个问题，一直不成功

**Comment by nosidedeng** [comment]
![image](https://github.com/Tencent/tdesign-starter-cli/assets/12694611/a50a7289-05e6-4a89-8352-bd93df8e6bdd)
我也遇到同样问题，新环境
![image](https://github.com/Tencent/tdesign-starter-cli/assets/12694611/a8748e7b-6eb2-4e03-b24c-7c21a157b5ed)

**Comment by uyarn** [comment]
这个问题我这两天反复确认 应该已经修复了 有需要可以再试试 如果还有问题可以重新打开issue
