### ISSUE TITLE
错误信息： RequestError: getaddrinfo ENOTFOUND github.com.cnpmjs.org

### ISSUE THREAD

**Issue by gmars** [Tencent/tdesign-starter-cli#7]
❗错误：下载模板失败
❗错误信息： RequestError: getaddrinfo ENOTFOUND github.com.cnpmjs.org
❗请尝试执行：git clone https://github.com/Tencent/tdesign-vue-next-starter.git 使用

[错误截图](https://oss.sikukeji.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20220209114302.png)

**Comment by uyarn** [comment]
感谢反馈 看起来镜像那边出问题了

**Comment by uyarn** [comment]
github.com.cnpmjs.org 这个镜像不维护了 这是没想到的.. 需要调整一下下载方式 ..

**Comment by chengpeiquan** [comment]
> github.com.cnpmjs.org 这个镜像不维护了 这是没想到的.. 需要调整一下下载方式 ..

我刚刚按照 [这个办法](https://zhuanlan.zhihu.com/p/445303816) 自己搭了一个 [https://create.preset.workers.dev/](https://create.preset.workers.dev/)，居然很顺利就跑起来了…
要不试试自己也弄一个？我前段时间 fastgit 挂了，然后找了一下来到这里，看你们用 CNPM ，本来还挺好用，结果过了个年就挂了…

**Comment by uyarn** [comment]
good 可以参考下 但是下周会发个新版本 先同步托管在coding or gitee 我们目前不想把事情做的太重

**Comment by uyarn** [comment]
close by https://github.com/Tencent/tdesign-starter-cli/pull/9
